name = "SemiclassicalOrthogonalPolynomials"
uuid = "291c01f3-23f6-4eb6-aeb0-063a639b53f2"
authors = ["Sheehan Olver <solver@mac.com>"]
version = "0.0.1"

[deps]
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
ContinuumArrays = "7ae1f121-cc2c-504b-ac30-9b923412ae5c"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
InfiniteArrays = "4858937d-0d70-526a-a4dd-2d5cb5dd786c"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrthogonalPolynomialsQuasi = "aa41a628-2c43-45df-899b-83ab96621781"
QuasiArrays = "c4ea9172-b204-11e9-377d-29865faadc5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
ArrayLayouts = "0.4"
BandedMatrices = "0.15.15"
ContinuumArrays = "0.3"
FillArrays = "0.10, 0.11"
HypergeometricFunctions = "0.3.4"
InfiniteArrays = "0.8"
LazyArrays = "0.19"
OrthogonalPolynomialsQuasi = "0.4"
QuasiArrays = "0.3"
SpecialFunctions = "0.10, 1.0"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
